[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wiithon"
description = "Wii ISO reading, patching and rebuilding library"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.md"]
authors = [{ name = "demorck" }]
keywords = [
    "wii", "nintendo",
    "iso", "rom-hacking", "patching", "reverse-engineering",
    "dol", "rarc", "bcsv", "u8", "lz77", "bnr"]

dynamic = ["version"]

classifiers = [
    "Development Status :: 3 - Alpha",

    "Intended Audience :: Developers",

    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",

    "Topic :: Software Development :: Disassemblers",
    "Topic :: Games/Entertainment",
    "Topic :: System :: Archiving",
    "Topic :: File Formats",

    "Typing :: Typed",
]

requires-python = ">=3.11"
dependencies = [
    "pycryptodome>=3.0",
    "typer>=0.9",
    "rich>=13.0",
]

[project.urls]
Homepage = "https://github.com/Demorck/wiithon"
Issues = "https://github.com/Demorck/wiithon/issues"
Documentation = "https://demorck.github.io/wiithon/"

[project.scripts]
wiithon = "wiithon.cli:app"

[project.optional-dependencies]
dev  = ["pytest>=8", "ruff>=0.6", "mypy>=1.11", "build"]
docs = ["sphinx>=7", "sphinx-rtd-theme", "sphinx-autodoc-typehints"]

[tool.ruff]
line-length = 120
src = ["src"]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "UP",
    "B",
    "SIM",
    "I",
    "ERA",

    # Type annotations. Excluded: tests
    "ANN",

    # Using assert in code
    "S101",

    # Generic exception
    "BLE",

    # Default Boolean argument needs to be refactored or keyword only arg (LSP) - Excluded: tests
    "FBT",

    # Shadowing python builtin
    "A",

    # Unecessary stuff
    "C4", "PIE",

    # Removing to-do stuff because no one reads them
    "FIX", "TD",

    # Impilict string concatenation - Excluded: tests
    "ISC",

    # Print/pprint found - Excluded: examples
    "T20",

    # Unecessary branch after return/raises
    "RET505", "RET506", "RET507", "RET508",

    # Private field access - Excluded: tests
    "SLF",

    # Unused arguments - Excluded: tests
    "ARG",

    # Using Pathlib instead of os - Excluded: tests (for now)
    "PTH",

    # Complexe structure, probably need a refactor
#    "C90"

    # PEP8 naming - Excluded: ppc, tests
    "N",

    # Changing stuff that lower performance
    "PERF",

    # Docstring,
#    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
#    "D414", "D416", "D417", "D419",

    # Magic number in comparison - Excluded: ppc
#    "PLR2004"
]

[tool.ruff.lint.per-file-ignores]
"examples/*"        = ["BLE", "T20", "PTH"]
"src/wiithon/cli/*" = ["FBT"]
"src/wiithon/ppc/*" = ["N", "PLR"]
"tests/*"           = ["ANN", "FBT", "ISC", "SLF", "ARG", "PTH", "N"]
"tests/iso/*"       = ["S101"]

[tool.ruff.lint.mccabe]
max-complexity = 13

[tool.mypy]
python_version = "3.11"
mypy_path = "src"
files = ["src/wiithon"]
warn_unused_ignores = true
disable_error_code = ["annotation-unchecked"]

[[tool.mypy.overrides]]
module = ["Crypto.*", "typer.*", "pytest.*", ]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "wiithon.builder.*",
    "wiithon.disc.*",
    "wiithon.formats.*",
    "wiithon.fst.*",
    "wiithon.ppc.*",
    "wiithon.cli",
]
ignore_errors = true

[tool.hatch.version]
path = "src/wiithon/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/wiithon"]
